# Generated by Django 5.0.6 on 2024-07-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_red'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Red',
        ),
    ]
