# Generated by Django 5.0.6 on 2024-07-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radar_distancia', models.FloatField()),
                ('radar_angulo', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('peso', models.FloatField()),
                ('gps_latitud', models.FloatField()),
                ('gps_longitud', models.FloatField()),
                ('gps_altitud', models.FloatField()),
                ('gps_velocidad', models.FloatField()),
            ],
        ),
    ]
